### ISSUE TITLE
collector_name environment variable does not work

### ISSUE THREAD

**Issue by mwaaas** [SumoLogic/sumologic-collector-docker#11]
container collector function does not work

log_forwarder:
  image: sumologic/collector:latest-syslog
  environment:
    - SUMO_ACCESS_ID=****
    - SUMO_ACCESS_KEY=****
    - SUMO_COLLECTOR_NAME=tumacredo_logs

But when the logs are forwarded and I do a search in sumologic the category is still collector-container

**Comment by duchatran** [comment]
You probably meant the collector name, not category. Anyway, I think the problem should be fixed by now. Feel free to reopen if this is not the case.
