### ISSUE TITLE
Rebuild images for glibc patch

### ISSUE THREAD

**Issue by someword** [SumoLogic/sumologic-collector-docker#14]
It looks like the existing sumologic-collector images do not have the glibc patch.   Can you please publish new images?

When I look at the ldd version on one of the collector images I get the following

```
docker run -it --entrypoint=ldd sumologic/collector:latest-syslog --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.6) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

When I look at the image that the collectors are based off of it looks to have been patched recently.
```
docker run -it ubuntu:14.04 ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6.7) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Info from ubuntu about the patch https://launchpad.net/ubuntu/+source/eglibc/2.19-0ubuntu6.7

**Comment by duchatran** [comment]
Thanks for notifying us. We have rebuilt all the images, please let us know if the problem persists.
