### ISSUE TITLE
Add a collector for journald collection

### ISSUE THREAD

**Issue by jimmycuadra** [SumoLogic/sumologic-collector-docker#17]
If you want to send journald logs to Sumo, there is currently [this method](https://www.sumologic.com/2015/04/03/collecting-journald-logs-with-sumo-logic/), but it would be great to have a collector image that understood journald directly without having to use that forwarding service.

**Comment by duchatran** [comment]
@jimmycuadra : I think our new docker native sources supports journald logs automatically. Can you check? These log sources are available with the appcollector image (https://hub.docker.com/r/sumologic/appcollector/)

**Comment by jimmycuadra** [comment]
I don't see a way to tell. There's nothing about it in the documentation. What's the difference between sumologic/collector and sumologic/appcollector? I was hoping for a way to configure this without giving the collector container direct access to the Docker socket.

**Comment by duchatran** [comment]
sumologic/collector:latest actually wont' run out of the box - you need to pick on of the other tags that predefine a Sumo source for the embedded Sumo collector  (e.g sumologic/collector:latest-file, or sumologic/collector:latest-syslog).

**Comment by jimmycuadra** [comment]
Thanks for the explanation. I believe this will work for me!
