### ISSUE TITLE
category as an environment variable

### ISSUE THREAD

**Issue by randomnumber9** [SumoLogic/sumologic-collector-docker#21]
Hi, 

In setting up our metadata tags when launching the sumologic collector, it would be nice to be able to set category as an environment variable at runtime.  Any thoughts to do this as a workaround?  Our category use changes and would like to run these with different values.

**Comment by duchatran** [comment]
Metadata tags are set at the source level typically, so they should be set inside "sumo.conf" (for the whole collector) or sources.json (for individual source - see for example: https://github.com/SumoLogic/sumologic-collector-docker/blob/master/docker-sources/sumo-sources.json).

**Comment by duchatran** [comment]
@randomnumber9: Latest build supports passing a custom sources.json (check under /docker-sources for an example of that file) via an environment parameter (SUMO_SOURCES_JSON), so you can specify the sourceCategory values.  Please reopen the issue if this doesn't work for you.
