### ISSUE TITLE
Multiple _sourceCategory for a single sumologic-collector-docker instance

### ISSUE THREAD

**Issue by devsprint** [SumoLogic/sumologic-collector-docker#24]
Hello,

I'm looking to see if there is a way to define multiple _sourceCategory per single container of sumologic-collector-docker. 
In my case, I'm running multiple docker containers in AWS ECS, all of them using the syslog docker logging driver. On each host I'm running sumologic-collector-docker (that is not managed by ecs-agent). All logs are arriving in Sumologic, but all of them under _sourceCategory= collector-container. Is there a way to have each docker container log going to its own _sourceCategory?

Thanks,

**Comment by duchatran** [comment]
@devsprint : The _sourceCategory is fixed for each collector source, so you'll need to craft your own sumo-sources.json (which defines your source meta data) and pass it to the container at run time.  See https://github.com/SumoLogic/sumologic-collector-docker/blob/master/docker-sources/sumo-sources.json for an example of such file. You need to provide the path to this new file via the environment SUMO_SOURCES_JSON (and of course mount your json file to the container) when you run it - see run.sh on a bunch of available other Environment variables. 
Let me know if it works for you.

**Comment by devsprint** [comment]
@duchatran it is not really a solution, it will not really work in a dynamic environment as Amazon ECS where docker containers are started/stopped, started on a new instance... what you are suggesting is that probably I have to update the script used to discover the docker containers running on a instance, produce a sumo-sources.json that will define source per container, and in case of a new service deployed, to basically restart sumo container to have the script being re-run...
For now I'm using a single instance per host, and to be able to trace I'm filtering the source with the  tag defined in ecs task for syslog docker log driver. This seems to work fine so far ...
Is there any API that could be used to interact with sumologic?
