### ISSUE TITLE
Set pathExpression via environmental variable

### ISSUE THREAD

**Issue by someword** [SumoLogic/sumologic-collector-docker#3]
Hello.
I'm walking through deploying a sumo logic collector docker container (thanks for making this available btw).  One feature that I think would be really handy is to be able to specify the pathExpression via an environment variable.  For example I could see many people wanting to run a container with a volume mapping like this.
/var/lib/docker/containers:/var/lib/docker/containers:ro

If i could specify the pathExpression as '/var/lib/docker/containers/**/*.log' via an environment variable that would lower the bar and serve what I think will be a common use case.    An alternative approach and possibly better would be to ship a few different sources.json with the container.  Then people could use the already available way to specify which flavor of sources.json they want to use.  I'd be happy to work on the latter case if that's agreeable.

**Comment by kumoroku** [comment]
Just seeing this now. Not sure where the notifications went. Let me take a look tonight.

**Comment by raychaser** [comment]
if i am understanding this correctly, you would like to have an easy way to just collect `/var/lib/docker/containers/**` which has all the JSON logs. in other words, wouldn't this do the trick?

```bash
docker run -v /var/lib/docker/containers:/tmp/clogs -d --name="sumo-logic-collector" sumologic/collector:latest-file [Access ID] [Access Key]
```

so the way that we are trying to make the collection path configurable is via the `-v` mapping. the source config is always looking at `/tmp/clogs` but what that actually points to is a function of the `-v` mapping that you specify when running the container.

let me know if i misunderstood the question, and sorry for taking so long to respond.

**Comment by someword** [comment]
Christian.
This could be a misunderstanding of sumologic on my part.

Docker default log path would look like this
/var/lib/docker/containers/<container_uuid>/<container_uuid>-json.log


Here is an actual example log path.
[root]# find /var/lib/docker -type f -name "*-json.log"
/var/lib/docker/containers/2de6c71261d0d7c75447b53cbfb974508b0332cc1ccac58e59deebd6d09a3265/2de6c71261d0d7c75447b53cbfb974508b0332cc1ccac58e59deebd6d09a3265-json.log
/var/lib/docker/containers/aceabf3c0919cfd3e3616e92df0db553e63e548c6d3d14be5f9e65df8e08cea3/aceabf3c0919cfd3e3616e92df0db553e63e548c6d3d14be5f9e65df8e08cea3-json.log
/var/lib/docker/containers/dc9b0bc45e4af20bb9cfc815b2b0e9c4012ca23e49c196158bcb115cb04853f0/dc9b0bc45e4af20bb9cfc815b2b0e9c4012ca23e49c196158bcb115cb04853f0-json.log
/var/lib/docker/containers/d703ba9f47902ed55eca3817b8be11cc7541666c24fce8065bc367b9dcf39bf2/d703ba9f47902ed55eca3817b8be11cc7541666c24fce8065bc367b9dcf39bf2-json.log

Will the "pathExpression": "/tmp/clogs/**"

match /tmp/clogs/<uuid>/<uuid>-json.log

I was under the impression it would not recurse through sub directories of
/tmp/clogs.   Am I misunderstanding?
Thanks. Derek

**Comment by kumoroku** [comment]
yes, `/tmp/clogs/**` will indeed recurse. please try - it should work!
