### ISSUE TITLE
Docker sources: _systemName from label

### ISSUE THREAD

**Issue by davidnortonjr** [SumoLogic/sumologic-collector-docker#30]
We are evaluating the SumoLogic Docker Sources collector. It's working great, but the `_sourceName` field comes from the container name, and our container names are generated by a clustering tool and do not provide enough information for us to determine the application.

Would there be a way to choose a container label to use in place of container name for the Sumo Logic field `_sourceName`, or perhaps to choose any number of labels to forward on under various field names?

**Comment by maimaisie** [comment]
Hi @davidnortonjr, thank you for using Sumo Logic. The `_sourceName` field for our Docker sources can only be mapped to the container name. May I ask if there are any labels in the log itself that are more useful than the container name? If so, have you tried setting up a field extraction rule? It can extract fields from your log messages and allow you to run searches using the extracted fields. Please check our documentation on this: https://help.sumologic.com/Manage/Search_Optimization_Tools/Manage_Field_Extractions

This link on Docker's log-opt settings might be also helpful: https://docs.docker.com/engine/admin/logging/log_tags/

**Comment by maimaisie** [comment]
Please also utilize Sumo Logic Support site for future questions as you will get more prompt answers from our support engineers: https://support.sumologic.com/ 
You can submit a support ticket by clicking on `Submit a request` on the top right corner of the page.
