### ISSUE TITLE
Runtime Env Subsitution

### ISSUE THREAD

**Issue by abecoffman** [SumoLogic/sumologic-collector-docker#32]
Our company is following a best practice you promote which is to `Control Who Sees What Data via RBAC`.
https://help.sumologic.com/Send_Data/01_Design_Your_Deployment/Best_Practices%3A_Good_Source_Category%2C_Bad_Source_Category

We have opted to put the `environment` (i.e. dev/uat/prod) into the sourceCategory string.  This presents a problem with running the collector in a container because the `sourceCategory` can't be dynamically resolved when the container is run.

Would you consider doing some sort of environment variable replacement on the source config in your ENTRYPOINT script?  Or perhaps provide another way of dynamically updating source configs when the container is run?  I'd like to be able to do something like this in the `sumo-sources.json`:

```json
{
    "category": "${environment}/component2/component3"
}
```

**Comment by maimaisie** [comment]
Hi @abecoffman, thank you for using the Sumo Logic Docker image. I assume you are using one of the pre-baked images that comes with a source configuration file, in fact you can use the custom image to build your own by providing your own version of `sumo-sources.json`. 

We have instructions here on how to build your own Sumo image: https://hub.docker.com/r/sumologic/collector/
Please scroll down to the bottom to the section "Custom Configuration". Let me know if you have questions.

**Comment by abecoffman** [comment]
Hi @maimaisie, thanks for the response.  I have tried using the custom configuration but it also doesn't support what I am after.  Are you familiar with Docker environment replacement?
https://docs.docker.com/engine/reference/builder/#/environment-replacement

In the `run.sh` script, you could run `sed` or some other function across the `sumo-sources.json` file(s) and replace any variables of the form `${variable_name}` just like docker does.

The reason I am asking for this is because I need to be able to resolve the `sourceCategory` when the image is run, not when it is built.  As of now, I am having to copy a different `sumo-sources.json` for each environment into the image at build time.  It works, but feels a bit hacky.

**Comment by stevezau** [comment]
Hi @abecoffman, i've just opened a PR that should address your request. Let me know what you think.

**Comment by abecoffman** [comment]
@stevezau thanks!
