### ISSUE TITLE
SUMO_COLLECTOR_NAME appending info at the beginning and end 

### ISSUE THREAD

**Issue by richarddowner** [SumoLogic/sumologic-collector-docker#43]
Hello, seem to be having a problem with the SUMO_COLLECTOR_NAME env variable. It adding naming information to the start and end of the collector name.

I have the collector name setup like this:
`SUMO_COLLECTOR_NAME=mycompany+myproject+webapi`

It is naming the collector as this:
`collector_container-mycompany+myproject+webapi-1491538595658`

I do not have the `SUMO_COLLECTOR_NAME_PREFIX` env variable set.
Is this working as intended? How can I make the collector name not append this info?

Cheers

**Comment by richarddowner** [comment]
Turns out the `-1491538595658` on the end was sumo creating a unique name for the collector as one with `...+webapi` already existed. However still unsure why I'm getting the `collector-container` at the beginning of the collector name.

**Comment by maimaisie** [comment]
Hi @richarddowner, you are correct about the `-1491538595658`. For `SUMO_COLLECTOR_NAME_PREFIX`, it has a default which is `collector_container-`. You can remove this prefix by setting `SUMO_COLLECTOR_NAME_PREFIX` to empty string `""`

**Comment by richarddowner** [comment]
Hi @maimaisie, thanks for your reply, however setting the `SUMO_COLLECTOR_NAME_PREFIX=""` still **does not** remove the `collector_container-` prefix.

**Comment by maimaisie** [comment]
@richarddowner That is unexpected. Are you sure a new collector with the same prefix appeared on the UI? I will try to repro and get back to you.

**Comment by richarddowner** [comment]
@maimaisie, yes I am sure. I have deleted the collector from Sumo, and redeployed the sumo-collector-docker service within ECS, the new collector registers with Sumo, but prepends the `collector_container-`. If you cannot replicate, I will try rebuilding my DockerFile as my version may be a little out of date.

**Comment by maimaisie** [comment]
I just tried and was able to get it working. Here's the docker run command that I used to create a sumo collector with docker sources:
```
docker run -d -e SUMO_COLLECTOR_NAME_PREFIX="" -e SUMO_COLLECTOR_NAME="maisie-docker-collector" -v /var/run/docker.sock:/var/run/docker.sock --name="sumologic
-collector" sumologic/collector:latest <access-id> <access-key>
```

**Comment by richarddowner** [comment]
Thanks @maimaisie, I will rebuild my DockerFile to update and report back. Thanks

**Comment by richarddowner** [comment]
Hi @maimaisie, looks like I was on the newest version of the sumo-collector-docker image. Its still adding the prefix `collector_containter-` even when `SUMO_COLLECTOR_NAME_PREFIX=""`

**Comment by maimaisie** [comment]
Can you show me how you are setting the variable or the docker command you used to redeploy collector? Maybe it's something specific to ECS, which I'm not very familiar with.

**Comment by richarddowner** [comment]
Here is the cloudformation snippet for the Task Definition running the Sumo Collector within AWS ECS

```
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Join ['', [!Ref 'AWS::StackName', -sumo_collector]]
      ContainerDefinitions:
      - Name: sumo_collector
        Cpu: 10
        Image: "xxxxxxxxxxxx.dkr.ecr.ap-southeast-2.amazonaws.com/sumo-collector:latest"
        Memory: 300
        Environment:
          -
            Name: SUMO_ACCESS_ID
            Value: !Ref 'SumoAccessId'
          - 
            Name: SUMO_ACCESS_KEY
            Value: !Ref 'SumoAccessKey'
          - 
            Name: SUMO_COLLECTOR_NAME
            Value: !Ref 'SumoCollectorName'
          - 
            Name: SUMO_COLLECTOR_NAME_PREFIX
            Value: ""
          - 
            Name: SUMO_PROXY_HOST
            Value: !Ref 'SumoProxyHost'
          - 
            Name: SUMO_PROXY_PORT
            Value: !Ref 'SumoProxyPort'
        PortMappings:
        - ContainerPort: 514
```

thanks

**Comment by maimaisie** [comment]
Does changing the value to something else work? I am not sure if ECS is reading the value `""` as empty string.

**Comment by richarddowner** [comment]
@maimaisie I just tested it by adding:
```
- 
            Name: SUMO_COLLECTOR_NAME_PREFIX
            Value: "pre"
```

Assuming my collector name is `MyCollector` this made the collector name: `preMyCollector`
So looks like the collector is ignoring the empty string and applying the prefix of `collector_containter-, but applying the prefix correctly when a non empty string is specified

**Comment by maimaisie** [comment]
Interesting, I have a feeling that ECS is not passing the empty value correctly. If you look at `run.sh` in this repo, you will see that the prefix is default to `collector_container-` only when it's not set

**Comment by richarddowner** [comment]
@maimaisie I just tried it with:
```
- 
            Name: SUMO_COLLECTOR_NAME_PREFIX
            Value: " "
```

Looks like this worked! The collector name is now as expected without any prefix. (It didn't add a space character to the beginning of the name either). 

Thanks for your help debugging this, appreciate it 👍

**Comment by maimaisie** [comment]
Glad it's working now! Although that is a little strange 😅

**Comment by richarddowner** [comment]
It is strange. I feel like default behaviour should be if no prefix is supplied, no prefix is applied. In the current state, if no prefix is supplied, `collector_container-` is applied.

**Comment by aleclarson** [comment]
I agree with @richarddowner here.

```sh
docker run -d -e SUMO_COLLECTOR_NAME=foo -e SUMO_COLLECTOR_NAME_PREFIX="" --restart=unless-stopped -v /var/run/docker.sock:/var/run/docker.sock --name="sumologic.collector" sumologic/collector:latest
```

With the above command, `collector_container-` is still used as the prefix. I'll see if `" "` works, but it would be nice if this was fixed.
