### ISSUE TITLE
best way to update collector.properties

### ISSUE THREAD

**Issue by kevinwsin** [SumoLogic/sumologic-collector-docker#45]
Hi, I just started playing around w/ this Docker image.  One question I have is: what's the best way to update the collector.properties, e.g. to add a `collector.syslog.udp.readBufferSize` property?  Haven't tried mounting a file over it yet but it seems like the file might be generated by the run.sh script.

**Comment by maimaisie** [comment]
Hi @kevinwsin , I believe you can follow these steps to see if it works:
1. Open a bash shell with the running collector container
`docker exec -ti <container_id or name>  /bin/bash`
2. Edit the file located at `/opt/SumoCollector/config/collector.properties`
3. Exit the shell
4. Restart the container
`docker restart `container_id or name`
5. After collector is running again, verify if the changes are applied

Please let me know if it works for you. Thanks!

**Comment by kevinwsin** [comment]
Thanks for the response.  I ended up using a non-Docker version b/c after updating following those steps, the messages were still being truncated for some reason.  It might just be some network setting in Docker.

**Comment by mhobotpplnet** [comment]
> Hi @kevinwsin , I believe you can follow these steps to see if it works:
> 
> 1. Open a bash shell with the running collector container
>    `docker exec -ti <container_id or name>  /bin/bash`
> 2. Edit the file located at `/opt/SumoCollector/config/collector.properties`
> 3. Exit the shell
> 4. Restart the container
>    `docker restart container_id or name`
> 5. After collector is running again, verify if the changes are applied
> 
> Please let me know if it works for you. Thanks!

This is just a manual work. I think that there should be an option to overwrite it..
