### ISSUE TITLE
Improper generation of JSON config if escape characters used.

### ISSUE THREAD

**Issue by rwadstein** [SumoLogic/sumologic-collector-docker#48]
There is a problem with the string substitution when running the `run.sh` and having the `\` escape character in the config.

Our regex has a valid JSON format using this for the multiline expression
```
"manualPrefixRegexp": "^\\[.*\\] \\[.*\\] \\[.*\\].*"
```

But when the `run.sh` command is run it strips the extra \ and outputs this:
```
"manualPrefixRegexp": "^\[.*\] \[.*\] \[.*\].*"
```

In order for us to get the proper format outputted, we had to add 6 slashes to have it generated properly.
```
"manualPrefixRegexp": "^\\\\\\[.*\\\\\\] \\\\\\[.*\\\\\\] \\\\\\[.*\\\\\\].*"
```

In order to avoid having each container have a crazy escape sequence of characters, we had to have another parser go through all our configs and generate one that conforms to the bug in collector script.

**Comment by maimaisie** [comment]
Hi @rwadstein , thanks for reporting the issue. Are you using a source json template file (like [this](https://github.com/SumoLogic/sumologic-collector-docker#source-templates))?

**Comment by rwadstein** [comment]
Yes, we followed that format.  We just happen to have a regex for the multi line prefix key with escape characters in the value that causes a problem when parsed out by the run.sh script.  If we run the collector manually in the docker container of our app, it reads it properly.

**Comment by rwadstein** [comment]
As far as I can tell, it seems to come from some this string substitution here.
https://github.com/SumoLogic/sumologic-collector-docker/blob/master/run.sh#L42

**Comment by kotowick** [comment]
Experiencing the same issue!

**Comment by maimaisie** [comment]
Hi @rwadstein and @kotowick , the fix has been merged and please let us know if you still encounter the same issue with the new images. Thanks.
