### ISSUE TITLE
Collector sends status too frequently

### ISSUE THREAD

**Issue by aaronbronow** [SumoLogic/sumologic-collector-docker#51]
Hi, I'm using this image to run a collector and with just 4 containers it's sending almost 1GB of logs per week. I assume that's because the status is sent often. Is there a way to set the frequency to something lower like every 5 minutes?

**Comment by bin3377** [comment]
Thanks for reporting the issue. If you are currently using `docker stats` source type, you can change the poll interval with Sumo Logic web UI or API

Let me know if that not resolve the problem or you are facing different problem

**Comment by bin3377** [comment]
https://github.com/SumoLogic/sumologic-collector-docker/pull/52

**Comment by aaronbronow** [comment]
Yeah, setting the poll interval in the web UI doesn't do anything. I was able to change the config file and rebuild the image.
