### ISSUE TITLE
Is SUMO_SYNC_SOURCES honored?

### ISSUE THREAD

**Issue by dkorel-copperleaf** [SumoLogic/sumologic-collector-docker#58]
When i set this variable it seems to be ignored... when i check in the UI, the collector is still set to cloud based management...

Is this a bug or am i doing something wrong?

**Comment by maimaisie** [comment]
Hi @dkorel-copperleaf, how are you setting the variable? Please provide steps or the exact "docker run" command you used. Thanks.

**Comment by dkorel-copperleaf** [comment]
Answered my own question!

so... after troubleshooting this for a while, it turns out the parameter we pass into the container needs to be
```SUMO_SYNC_SOURCES: "true"```
and not
```SUMO_SYNC_SOURCES: true```
the later is converted to True in the environment and ignored.
