### ISSUE TITLE
Tag releases in docker hub

### ISSUE THREAD

**Issue by cnuss** [SumoLogic/sumologic-collector-docker#7]
Hey there,

All your versions in docker hub are "latest".  We'd like to control our version updates, could you start pushing distinct versions of the containers?

Thanks
Chrisitan

**Comment by felixSchl** [comment]
I am also interested to see distinct tags being pushed to dockerhub to ensure longevity of our deployments.

**Comment by duchatran** [comment]
Thanks @cnuss , @felixSchl . Just so I understand your use cases, are you looking for tagging for the master branch build, or all the builds we have?

**Comment by cnuss** [comment]
@duchatran creating tags strictly for releases of the collector would be great

it looks like you don't specify a particular version of the collector in the Dockerfile, but if you could, having the tag relate to that would be wonderful

**Comment by duchatran** [comment]
@cnuss: Since we will also update the container image to incorporate new collector builds while everything else is the same, we probably won't put any version in the Dockerfile but tag the image instead. Hope this is good for you guys.
