### ISSUE TITLE
SUMO_COLLECTOR_NAME_PREFIX not working

### ISSUE THREAD

**Issue by jmreicha** [SumoLogic/sumologic-collector-docker#70]
Setting the `SUMO_COLLECTOR_NAME_PREFIX=""` as shown in the documentation does not remove the `collector_container-` prefix in Sumologic.  I ran across https://github.com/SumoLogic/sumologic-collector-docker/issues/43 which describes this.

It looks like the workaround is to use an extra space in the variable, e.g. 

```SUMO_COLLECTOR_NAME_PREFIX=" "```

Is this intended or is this a bug?  If intended, can I update the README?

**Comment by maimaisie** [comment]
Hi @jmreicha , are you also using AWS ECS?

**Comment by jmreicha** [comment]
@maimaisie Nope, using Kubernetes.  I _think_ the bug is [here](https://github.com/SumoLogic/sumologic-collector-docker/blob/master/run.sh#L17).
