### ISSUE TITLE
Re-creating collector container results in repeat log entries

### ISSUE THREAD

**Issue by pbitty** [SumoLogic/sumologic-collector-docker#8]
Hi, I've found that if I have a container pointed at local file sources on the host, and I re-create this container pointing at the same sources, I'll see repeat log messages in SumoLogic (ie: same timestamp, but different receipt time).

It seems that a newly created container will have completely new state and it will re-scan lines that have already been collected by the previous container.  Is there a way around this?

Could I mount a directory as a volume to persist state between collector containers?

**Comment by duchatran** [comment]
Each collector instance inside a container has its own space to keep track of its configurations, a shared space can lead to conflict among the collectors. To avoid duplication, a local file source should be read by a unique collector source (across all collectors and even within the same collector). If you want to preserve the states of the sources across multiple - non-simultanous runs, you can try to mount the "config" folder to somewhere on the docker host - but I have never tried it so not sure if this will work.
