### ISSUE TITLE
Maximum 100 containers per host for docker sources

### ISSUE THREAD

**Issue by nhoughto** [SumoLogic/sumologic-collector-docker#88]
While evaluating the docker sources in comparison to our current approach of using logfwd (https://github.com/bsycorp/log-forwarder/) we bumped up against the possibly arbitrary limit of 100 containers max and 40 default for collecting logs. In terms of monitoring a Kubernetes node, the default node pod limit is 110, and each pod can have multiple containers so all default deployments are going to be above this limit, we configure some of our clusters with have 200+ pods on them. Can the limit be raised above 100? Should it be? Is the log collection an expensive process thus the limit?

We like our current logfwd solution, but it seems like the http hosted collector is a second class citizen vs the proper agent collector thus looking at official solutions.

Doco:
https://github.com/SumoLogic/sumologic-collector-docker#to-monitor-more-than-40-containers

**Comment by maimaisie** [comment]
Hi @nhoughto , if you are running Kubernetes, we recommend using our Kubernetes monitoring solution available here https://github.com/SumoLogic/sumologic-kubernetes-collection

**Comment by nhoughto** [comment]
Ah interesting, didn't know that existed.

So there is no official way of supporting Kubernetes logging without using a HTTP Hosted collector? We currently do that via logfwd but bump up against strange behaviour around multi-line messages that the agent collector doesn't seem to have the same troubles with.
The docker sources for agent collector should avoid problem (bc not using HTTP hosted collector).

So what i'm hearing is the 100 limit isn't actually a limit, its not enforced and its arbitrary, but the idiomatic way to do kube for sumo is that separate project, which has its own problems.. 🤔 

Good info either way, thanks.
